### ISSUE TITLE
https://github.com/NocturaServices/Frontend.git is not found on github

### ISSUE THREAD

**Issue by T3M1N4L** [NebulaServices/Noctura#19]

**Comment by builtbyvys** [comment]
@T3M1N4L This is probably because of the migration of organizations. I've gone ahead and pushed a commit to the [README.md](https://github.com/NebulaServices/Noctura/commit/3e7c30dc616ba5832d3b552095a114c92ba6f2e3) if you still haven't been able to clone this repository, and for anyone trying to clone following the [README.md](https://github.com/NebulaServices/Noctura/blob/main/README.md) in the future.
